name: 'platformOS/RunTestCafeTest'
description: run TestCafe test
inputs:
  test-name:
    description: 'test name'
    required: true
  before:
    required: false
  after:
    required: false
  skip:
    required: false
  npm-prefix:
    required: false
    default: "."
runs:
  using: "composite"
  steps:

      - name: before ${{ inputs.test-name }}
        if: ${{ inputs.before && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.before }}

      - name: run ${{ inputs.test-name }}
        env:
          REPORT_TYPE: ${{ inputs.test-name }}
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          set -e
          echo -----REPORT-URL------
          echo $UPLOAD_HOST/$REPORT_PATH-$REPORT_TYPE
          echo --------------
          npm run ${{ inputs.test-name }} --prefix ${{ inputs.npm-prefix }}

      - name: after ${{ inputs.test-name }}
        if: ${{ inputs.after && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.after }}

      - name: publish report ${{ inputs.test-name }}
        if: ${{ inputs.test-name != 'tc-update-base-snapshots' && !inputs.skip && always() }}
        shell: sh
        run: |
          set -eu

          REPORT_TYPE=${{ inputs.test-name }}
          UPLOAD_PATH=api/app_builder/marketplace_releases/sync

          curl -sSf -XPUT $UPLOAD_HOST/$UPLOAD_PATH -H "Authorization: Token $MPKIT_TOKEN" \
            -F "marketplace_builder_file_body=@${{ inputs.npm-prefix }}/test-report.html" \
            -F "path=app/views/pages/$REPORT_PATH-$REPORT_TYPE/index.liquid" \
            -o /dev/null

          echo test report uploaded: $UPLOAD_HOST/$REPORT_PATH-$REPORT_TYPE

      - name: summary
        if: ${{ inputs.test-name != 'tc-update-base-snapshots' && !inputs.skip && failure() }}
        shell: sh
        run: |
          REPORT_TYPE=${{ inputs.test-name }}
          echo "### FAILED $REPORT_TYPE tests report -> $UPLOAD_HOST/$REPORT_PATH-$REPORT_TYPE" >> $GITHUB_STEP_SUMMARY

      - name: skip ${{ inputs.test-name }}
        if: ${{ !!inputs.skip }}
        shell: sh
        run: echo skipping ${{ inputs.test-name }}
